
import java.util.Random;
import javax.swing.JButton;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thant Zin
 */
public class FourByFourFrame extends javax.swing.JFrame {

    /**
     * Creates new form FourByFourFrame
     */
    public FourByFourFrame() {
        initComponents();
    }
    public void checkSoln(){
        String b1 = I.getText();
        String b2 = II.getText();
        String b3 = III.getText();
        String b4 = IV.getText();
        String b5 = V.getText();
        String b6 = VI.getText();
        String b7 = VII.getText();
        String b8 = VIII.getText();
        String b9 = IX.getText();
        String b10 = X.getText();
        String b11 = XI.getText();
        String b12= XII.getText();
        String b13 = XIII.getText();
        String b14 = XIV.getText();
        String b15 = XV.getText();
        if(b1.equals("1") && b2.equals("2")&& b3.equals("3")&& b4.equals("4")&& b5.equals("5")&& b6.equals("6")
                && b7.equals("7")&& b8.equals("8")&& b9.equals("9")&& b10.equals("10")&& b11.equals("11")&& b12.equals("12")&& b13.equals("13")
                && b14.equals("14")&& b15.equals("15")){
            timer.stop();
            Congratulation c = new Congratulation();
            c.cseconds = seconds;
            c.cminutes = minutes;
            c.countR = counter;
            c.level = "4*4";
            c.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        timerValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        countValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        play = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        I = new javax.swing.JButton();
        IV = new javax.swing.JButton();
        II = new javax.swing.JButton();
        VIII = new javax.swing.JButton();
        III = new javax.swing.JButton();
        XII = new javax.swing.JButton();
        V = new javax.swing.JButton();
        XIV = new javax.swing.JButton();
        VI = new javax.swing.JButton();
        XIII = new javax.swing.JButton();
        VII = new javax.swing.JButton();
        XVI = new javax.swing.JButton();
        IX = new javax.swing.JButton();
        XV = new javax.swing.JButton();
        X = new javax.swing.JButton();
        XI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 185, 250));

        jPanel4.setBackground(new java.awt.Color(223, 141, 32));
        jPanel4.setForeground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        jLabel2.setText("Timer");

        timerValue.setBackground(new java.awt.Color(223, 141, 32));
        timerValue.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        timerValue.setForeground(new java.awt.Color(255, 255, 255));
        timerValue.setText("10:00");
        timerValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timerValue)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(223, 141, 32));

        countValue.setBackground(new java.awt.Color(0, 51, 51));
        countValue.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        countValue.setForeground(new java.awt.Color(255, 255, 255));
        countValue.setText("0");

        jLabel1.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        jLabel1.setText("Move Count");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(countValue, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countValue)
                .addGap(12, 12, 12))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        play.setBackground(new java.awt.Color(0, 0, 0));
        play.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setText("Resume");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(start, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(play, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 185, 250));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setBackground(new java.awt.Color(153, 185, 250));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lyingnuggie.png"))); // NOI18N
        jPanel6.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 114));

        jPanel5.setBackground(new java.awt.Color(185, 232, 252));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        I.setBackground(new java.awt.Color(255, 255, 204));
        I.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        I.setText("1");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        jPanel5.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 55, 52));

        IV.setBackground(new java.awt.Color(255, 204, 204));
        IV.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        IV.setText("4");
        IV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IVActionPerformed(evt);
            }
        });
        jPanel5.add(IV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 55, 52));

        II.setBackground(new java.awt.Color(255, 204, 255));
        II.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        II.setText("2");
        II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IIActionPerformed(evt);
            }
        });
        jPanel5.add(II, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 55, 52));

        VIII.setBackground(java.awt.Color.red);
        VIII.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        VIII.setText("8");
        VIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIIIActionPerformed(evt);
            }
        });
        jPanel5.add(VIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 55, 52));

        III.setBackground(new java.awt.Color(204, 255, 204));
        III.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        III.setText("3");
        III.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IIIActionPerformed(evt);
            }
        });
        jPanel5.add(III, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 55, 52));

        XII.setBackground(new java.awt.Color(153, 153, 0));
        XII.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XII.setText("12");
        XII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XIIActionPerformed(evt);
            }
        });
        jPanel5.add(XII, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 55, 52));

        V.setBackground(java.awt.Color.cyan);
        V.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        V.setText("5");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        jPanel5.add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 55, 52));

        XIV.setBackground(java.awt.Color.orange);
        XIV.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XIV.setText("14");
        XIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XIVActionPerformed(evt);
            }
        });
        jPanel5.add(XIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 55, 52));

        VI.setBackground(java.awt.Color.yellow);
        VI.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        VI.setText("6");
        VI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIActionPerformed(evt);
            }
        });
        jPanel5.add(VI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 55, 52));

        XIII.setBackground(new java.awt.Color(243, 186, 245));
        XIII.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XIII.setText("13");
        XIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XIIIActionPerformed(evt);
            }
        });
        jPanel5.add(XIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 55, 52));

        VII.setBackground(java.awt.Color.green);
        VII.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        VII.setText("7");
        VII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIIActionPerformed(evt);
            }
        });
        jPanel5.add(VII, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 55, 52));

        XVI.setBackground(new java.awt.Color(51, 51, 255));
        XVI.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XVIActionPerformed(evt);
            }
        });
        jPanel5.add(XVI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 55, 52));

        IX.setBackground(java.awt.SystemColor.textHighlight);
        IX.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        IX.setText("9");
        IX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXActionPerformed(evt);
            }
        });
        jPanel5.add(IX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 55, 52));

        XV.setBackground(new java.awt.Color(204, 102, 0));
        XV.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XV.setText("15");
        XV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XVActionPerformed(evt);
            }
        });
        jPanel5.add(XV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 55, 52));

        X.setBackground(new java.awt.Color(204, 0, 255));
        X.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        X.setText("10");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        jPanel5.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 55, 52));

        XI.setBackground(new java.awt.Color(0, 153, 153));
        XI.setFont(new java.awt.Font("STHupo", 1, 20)); // NOI18N
        XI.setText("11");
        XI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XIActionPerformed(evt);
            }
        });
        jPanel5.add(XI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 55, 52));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 280));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void dis(){
        I.setEnabled(false);
        II.setEnabled(false);
        III.setEnabled(false);
        IV.setEnabled(false);
        V.setEnabled(false);
        VI.setEnabled(false);
        VII.setEnabled(false);
        VIII.setEnabled(false);
        IX.setEnabled(false);
        X.setEnabled(false);
        XI.setEnabled(false);
        XII.setEnabled(false);
        XIII.setEnabled(false);
        XIV.setEnabled(false);
        XV.setEnabled(false);
        XVI.setEnabled(false);
    }
    private void ena(){
        I.setEnabled(true);
        II.setEnabled(true);
        III.setEnabled(true);
        IV.setEnabled(true);
        V.setEnabled(true);
        VI.setEnabled(true);
        VII.setEnabled(true);
        VIII.setEnabled(true);
        IX.setEnabled(true);
        X.setEnabled(true);
        XI.setEnabled(true);
        XII.setEnabled(true);
        XIII.setEnabled(true);
        XIV.setEnabled(true);
        XV.setEnabled(true);
        XVI.setEnabled(true);
    }
    private Timer timer;
    public int seconds = 0;
    public int minutes = 0;
    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        EmptySpotChecker(X,IX);
        EmptySpotChecker(X,VI);
        EmptySpotChecker(X,XI);
        EmptySpotChecker(X,XIV);
    }//GEN-LAST:event_XActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        shuffle();
        dis();
        play.setVisible(false);
        jButton2.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        EmptySpotChecker(I,II);
        EmptySpotChecker(I,V);
        checkSoln();
    }//GEN-LAST:event_IActionPerformed

    private void IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IIActionPerformed
       EmptySpotChecker(II,I);
        EmptySpotChecker(II,III);
        EmptySpotChecker(II,VI);
        checkSoln();
    }//GEN-LAST:event_IIActionPerformed

    private void IIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IIIActionPerformed
        EmptySpotChecker(III,II);
        EmptySpotChecker(III,VII);
        EmptySpotChecker(III,IV);
        checkSoln();
    }//GEN-LAST:event_IIIActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        EmptySpotChecker(V,I);
        EmptySpotChecker(V,VI);
        EmptySpotChecker(V,IX);
        checkSoln();
    }//GEN-LAST:event_VActionPerformed

    private void VIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIActionPerformed
        EmptySpotChecker(VI,II);
        EmptySpotChecker(VI,V);
        EmptySpotChecker(VI,VII);
        EmptySpotChecker(VI,X);
        checkSoln();
    }//GEN-LAST:event_VIActionPerformed

    private void VIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIIActionPerformed
        EmptySpotChecker(VII,III);
        EmptySpotChecker(VII,VI);
        EmptySpotChecker(VII,XI);
        EmptySpotChecker(VII,VIII);
        checkSoln();
    }//GEN-LAST:event_VIIActionPerformed

    private void IXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXActionPerformed
         EmptySpotChecker(IX,V);
        EmptySpotChecker(IX,X);
        EmptySpotChecker(IX,XIII);
        checkSoln();
    }//GEN-LAST:event_IXActionPerformed

    private void XIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XIActionPerformed
        EmptySpotChecker(XI,VII);
        EmptySpotChecker(XI,X);
        EmptySpotChecker(XI,XV);
        EmptySpotChecker(XI,XII);
        checkSoln();
    }//GEN-LAST:event_XIActionPerformed

    private void IVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IVActionPerformed
        EmptySpotChecker(IV,III);
        EmptySpotChecker(IV,VIII);
        checkSoln();
       
    }//GEN-LAST:event_IVActionPerformed

    private void VIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIIIActionPerformed
        EmptySpotChecker(VIII,XII);
        EmptySpotChecker(VIII,VII);
        EmptySpotChecker(VIII,IV);
        checkSoln();
       
    }//GEN-LAST:event_VIIIActionPerformed

    private void XIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XIIActionPerformed
        EmptySpotChecker(XII,XI);
        EmptySpotChecker(XII,XVI);
        EmptySpotChecker(XII,VIII);
        checkSoln();
    }//GEN-LAST:event_XIIActionPerformed

    private void XIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XIVActionPerformed
        EmptySpotChecker(XIV,XIII);
        EmptySpotChecker(XIV,X);
        EmptySpotChecker(XIV,XV);
        checkSoln();
    }//GEN-LAST:event_XIVActionPerformed

    private void XIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XIIIActionPerformed
        EmptySpotChecker(XIII,IX);
        EmptySpotChecker(XIII,XIV);
        checkSoln();
    }//GEN-LAST:event_XIIIActionPerformed

    private void XVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XVIActionPerformed
        EmptySpotChecker(XVI,XII);
        EmptySpotChecker(XVI,XV);
        checkSoln();
    }//GEN-LAST:event_XVIActionPerformed

    private void XVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XVActionPerformed
        EmptySpotChecker(XV,XIV);
        EmptySpotChecker(XV,XVI);
        EmptySpotChecker(XV,XI);
        checkSoln();
    }//GEN-LAST:event_XVActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        //activate keys
        timer.start();
       System.out.println(seconds);
       jButton2.setVisible(true);
       play.setVisible(false);
       ena();
        
    }//GEN-LAST:event_playActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setVisible(false);
        timer.stop();
        play.setVisible(true);
        dis();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        //activate keys
        jButton2.setVisible(true);
        ena();
        start.setVisible(false);
        ////////////////////////////////////////////////////

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                seconds++;
                if(seconds >= 59 ){
                    minutes += 1;
                    seconds = 0;
                }
                if(minutes==3){
                    timer.stop();
                    TimeUp1 tu = new TimeUp1();
                    tu.setVisible(true);
                    dis();
                    start.setVisible(false);
                    jButton2.setVisible(false);
                }

                ////////////////////Design timer////////////////////////////
                if(seconds<10 && minutes < 10){
                    timerValue.setText("0"+minutes+" : "+"0"+seconds);
                }else if(seconds<10){
                    timerValue.setText(minutes+" : "+"0"+seconds);
                }else if(minutes<10){
                    timerValue.setText("0"+minutes+" : "+seconds);
                }else if(seconds>10 && minutes>10){
                    timerValue.setText(minutes+" : "+seconds);
                }
            }
        });

        // Start the timer
        timer.start();
    }//GEN-LAST:event_startActionPerformed
    private void stopTimer() {
    if (seconds == 3) {
        timer.stop();
    }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Puzzle_level hp = new Puzzle_level();
        hp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // main section ===================================
    
    int counter = 0;
    void EmptySpotChecker(JButton Butt1,JButton Butt2){
        String shuffleNumber = Butt2.getText();
        if(shuffleNumber == ""){
            Butt2.setText(Butt1.getText());
            Butt1.setText("");
            setCounter();
            new Thread() {
                @Override
                public void run() {
                    Sound sound = null;
                    try {
                        sound
                                = new Sound(getClass().getResource("/sounds/guess.wav"));
                    } catch (Exception e) {
                    }
                    InputStream stream
                            = new ByteArrayInputStream(sound.getSamples());
                    sound.play(stream);
                }
            }.start();//sound 
        }
        
    }
    
    public void shuffle(){
        int minValue = 1;
        int maxValue = 15;
        int count = maxValue - minValue + 1;

        int[] nonRedundantRandomNumbers = generateNonRedundantRandomNumbers(minValue, maxValue, count);

//        I.setText(Integer.toString(nonRedundantRandomNumbers[1]));
//        II.setText(Integer.toString(nonRedundantRandomNumbers[2]));
//        III.setText(Integer.toString(nonRedundantRandomNumbers[3]));
//        V.setText(Integer.toString(nonRedundantRandomNumbers[4]));
//        VI.setText(Integer.toString(nonRedundantRandomNumbers[5]));
//        VII.setText(Integer.toString(nonRedundantRandomNumbers[6]));
//        IX.setText(Integer.toString(nonRedundantRandomNumbers[7]));
//        X.setText(Integer.toString(nonRedundantRandomNumbers[8]));
//        XI.setText(Integer.toString(nonRedundantRandomNumbers[9]));
//        XIII.setText(Integer.toString(nonRedundantRandomNumbers[10]));
//        XIV.setText(Integer.toString(nonRedundantRandomNumbers[11]));
//        XV.setText(Integer.toString(nonRedundantRandomNumbers[12]));
//        XVI.setText("");
//        IV.setText(Integer.toString(nonRedundantRandomNumbers[14]));
//        VIII.setText(Integer.toString(nonRedundantRandomNumbers[0]));
//        XII.setText(Integer.toString(nonRedundantRandomNumbers[13]));
          if (nonRedundantRandomNumbers[0]==1|| nonRedundantRandomNumbers[0] ==3|| nonRedundantRandomNumbers[0] ==5||
                  nonRedundantRandomNumbers[0] ==7|| nonRedundantRandomNumbers[0] ==9|| nonRedundantRandomNumbers[0] ==11||
                  nonRedundantRandomNumbers[0] ==13|| nonRedundantRandomNumbers[0] ==15){
              I.setText("3");
              II.setText("2");
              III.setText("14");
              IV.setText("5");
              V.setText("1");
              VI.setText("10");
              VII.setText("4");
              VIII.setText("9");
              IX.setText("15");
              X.setText("13");
              XI.setText("12");
              XII.setText("11");
              XIII.setText("8");
              XIV.setText("6");
              XV.setText("7");
              XVI.setText("");
          }
          
          if (nonRedundantRandomNumbers[0]==2 || nonRedundantRandomNumbers[0] ==4|| nonRedundantRandomNumbers[0] ==6 ||
                  nonRedundantRandomNumbers[0] ==8 || nonRedundantRandomNumbers[0] ==10 || nonRedundantRandomNumbers[0] ==12 
                  || nonRedundantRandomNumbers[0] ==14){
              I.setText("15");
              II.setText("5");
              III.setText("14");
              IV.setText("11");
              V.setText("10");
              VI.setText("3");
              VII.setText("4");
              VIII.setText("1");
              IX.setText("2");
              X.setText("8");
              XI.setText("9");
              XII.setText("7");
              XIII.setText("13");
              XIV.setText("6");
              XV.setText("12");
              XVI.setText("");
          }
        
       
    }
    
    public static int[] generateNonRedundantRandomNumbers(int minValue, int maxValue, int count) {
        if (count > (maxValue - minValue + 1)) {
            throw new IllegalArgumentException("Count must be less than or equal to the range.");
        }

        int[] randomNumbers = new int[count];
        boolean[] usedNumbers = new boolean[maxValue - minValue + 1];
        Random random = new Random();

        for (int i = 0; i < count; i++) {
            int randomNumber;
            do {
                randomNumber = random.nextInt(maxValue - minValue + 1) + minValue;
            } while (usedNumbers[randomNumber - minValue]);

            randomNumbers[i] = randomNumber;
            usedNumbers[randomNumber - minValue] = true;
        }
        
        return randomNumbers;
    }
    
    private void setCounter(){
        counter += 1;
        System.out.println("current count" + counter);
        countValue.setText(String.valueOf(counter));
    }
    
    // ==================================================
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourByFourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourByFourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourByFourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourByFourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourByFourFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton I;
    private javax.swing.JButton II;
    private javax.swing.JButton III;
    private javax.swing.JButton IV;
    private javax.swing.JButton IX;
    private javax.swing.JButton V;
    private javax.swing.JButton VI;
    private javax.swing.JButton VII;
    private javax.swing.JButton VIII;
    private javax.swing.JButton X;
    private javax.swing.JButton XI;
    private javax.swing.JButton XII;
    private javax.swing.JButton XIII;
    private javax.swing.JButton XIV;
    private javax.swing.JButton XV;
    private javax.swing.JButton XVI;
    private javax.swing.JLabel countValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblImage;
    private javax.swing.JButton play;
    private javax.swing.JButton start;
    private javax.swing.JLabel timerValue;
    // End of variables declaration//GEN-END:variables
}
