

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thant Zin
 */
public class matchLeaderboard extends javax.swing.JFrame {
    String names[];
    String pname;
    String minutes;
    String seconds;
    String counts;
    String level;
    int length;

    /**
     * Creates new form matchLeaderboard
     */
    public matchLeaderboard() {
        initComponents();
        Icon i = lblImage.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        lblImage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fbf = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 185, 250));

        fbf.setBackground(new java.awt.Color(223, 141, 32));
        fbf.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        fbf.setText("4*4");
        fbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbfActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(223, 141, 32));
        back.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        tbt.setBackground(new java.awt.Color(223, 141, 32));
        tbt.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        tbt.setText("3*3");
        tbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 153, 0), null, null));
        jTable1.setFont(new java.awt.Font("STHupo", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial no.", "Player Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Hello");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(10);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setBackground(new java.awt.Color(223, 141, 32));
        jComboBox1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alphabetical", "Max to Min", "Min to Max" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(223, 141, 32));
        jLabel1.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        jLabel1.setText("Matching Ranking table");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot__28_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fbf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(fbf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbfActionPerformed
        this.setVisible(false);
        fbfLeader fbf = new fbfLeader();
        fbf.setVisible(true);
    }//GEN-LAST:event_fbfActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.setVisible(false);
       leaderboard fbf = new leaderboard();
        fbf.setVisible(true);
       
    }//GEN-LAST:event_backActionPerformed

    private void tbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtActionPerformed
        tbtLeaderboard tbt = new tbtLeaderboard();
        tbt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbtActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_puzzle","root","");
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("select * from match_game");
            int i=0;
            while(rs.next()){
                i+=1;
                System.out.println(rs.getString("name")+rs.getInt("score"));
                String tbData[] = {String.valueOf(i),rs.getString("name"),String.valueOf(rs.getInt(2))};
                DefaultTableModel leaderboard = (DefaultTableModel)jTable1.getModel();
                leaderboard.addRow(tbData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(matchLeaderboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(matchLeaderboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> allData = new ArrayList<>(); // To store all data
        ArrayList<String> allNames = new ArrayList<>();
        ArrayList<Integer> allScores = new ArrayList<Integer>();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_puzzle","root","");
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("select * from match_game");
            int i=0;
            while(rs.next()){
                i+=1;
                System.out.println(rs.getString("name")+rs.getInt("score"));
                String ranking = String.valueOf(i);
                String pname = rs.getString("name");
                String scores = String.valueOf(rs.getInt("score"));
                //String tbData[] = {String.valueOf(i),rs.getString("name"),String.valueOf(rs.getInt(2))};
                //DefaultTableModel leaderboard = (DefaultTableModel)jTable1.getModel();
                //leaderboard.addRow(tbData);
                String[] rowData = {ranking, pname, scores};
                allData.add(rowData);
                allScores.add(Integer.parseInt(scores));
    
    // Add the name to allNames
                allNames.add(pname);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(matchLeaderboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(matchLeaderboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        matchLeaderboard sorter = new matchLeaderboard();
        String s = jComboBox1.getSelectedItem().toString();
        if (s == "Alphabetical"){
            
            String[] words = allNames.toArray(new String[0]);// the strings needa to be sorted are put inside this array String words[] = {"zz", "aa", "cc", "hh", "bb", "ee", "ll"};
            sorter.sort1(words);
            
            DefaultTableModel leaderboard = (DefaultTableModel) jTable1.getModel();
            leaderboard.setRowCount(0);
       
        //leaderboard.addRow(words);
            int p =0;
        
            for (String name : words) {
                p += 1;
                String ranking = String.valueOf(p);
                for (String[] data : allData) {
                    if (data[1].equals(name)) { // Check if the name matches
                    //rowData = data;
                        Object[] rowData = {ranking,name,data[2]};
                        leaderboard.addRow(rowData);
                    //break;
                    }
                }
            //Object[] rowData = {ranking,name};
            
            }
        }
        if (s == "Max to Min"){
            int[] score1 = new int[allScores.size()];
            for (int k=0; k< allScores.size(); k++){
                score1[k] = allScores.get(k);
            }
            Arrays.sort(score1);
            for (int a = 0; a < score1.length / 2; a++) {
            int temp = score1[a];
            score1[a] = score1[score1.length - 1 - a];
            score1[score1.length - 1 - a] = temp;
            }
            DefaultTableModel leaderboard = (DefaultTableModel) jTable1.getModel();
            leaderboard.setRowCount(0);
            String[] names = new String[allNames.size()];
            int b =0;
            int c = 0;
            //int i = 0;
            for (int sec : score1) {
            b += 1;
            String ranking = String.valueOf(b);
            String sec1 = Integer.toString(sec);
            int i = 0;
            for (String[] data : allData) {
                for (int x=0; x<c; x++){
                    i = 0;
                    if (names[x].equals(data[1]) ){
                    i = 1;
                    }
                    }
                if (data[2].equals(sec1 )&& i != 1) { // Check if the name matches
                    //rowData = data;
                    names[c] = data[1];
                    Object[] rowData = {ranking,data[1],data[2]};
                    leaderboard.addRow(rowData);
                    break;
                }
            }
            //Object[] rowData = {ranking,name};
            c += 1;
        }
        }
        if (s == "Min to Max"){
            //int[] time =allSeconds.toArray(new int[0])
            int[] time = new int[allScores.size()];
            for (int k=0; k< allScores.size(); k++){
                time[k] = allScores.get(k);
            }
            int size = time.length;
            matchLeaderboard.quickSort(time, 0, size - 1);
            DefaultTableModel leaderboard = (DefaultTableModel) jTable1.getModel();
            leaderboard.setRowCount(0);
            int l =0;
            String[] names = new String[allNames.size()];
            int b =0;
            int c = 0;
            int i = 0;
            for (int sec : time) {
            l += 1;
            String ranking = String.valueOf(l);
            String sec1 = Integer.toString(sec);
            
            for (String[] data : allData) {
                for (int x=0; x<c; x++){
                    i = 0;
                    if (names[x].equals(data[1])){
                    i = 1;
                    }
                    }
                if (data[2].equals(sec1) && i!=1) { // Check if the name matches
                    //rowData = data;
                    names[c] = data[1];
                    Object[] rowData = {ranking,data[1],data[2]};
                    leaderboard.addRow(rowData);
                    break;
                }
            }
            c += 1;//Object[] rowData = {ranking,name};
            
        }
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchLeaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton fbf;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JButton tbt;
    // End of variables declaration//GEN-END:variables
        void sort(String[] words) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    void sort1(String array[]) {
        if (array == null || array.length == 0) {
            return;
        }
        this.names = array;
        this.length = array.length;
        quickSort(0, length - 1);
    }

    void quickSort(int lowerIndex, int higherIndex) {
        int i = lowerIndex;
        int j = higherIndex;
        String pivot = this.names[lowerIndex + (higherIndex - lowerIndex) / 2];

        while (i <= j) {
            while (this.names[i].compareToIgnoreCase(pivot) < 0) {
                i++;
            }

            while (this.names[j].compareToIgnoreCase(pivot) > 0) {
                j--;
            }

            if (i <= j) {
                exchangeNames(i, j);
                i++;
                j--;
            }
        }
        //call quickSort recursively
        if (lowerIndex < j) {
            quickSort(lowerIndex, j);
        }
        if (i < higherIndex) {
            quickSort(i, higherIndex);
        }
    }

    void exchangeNames(int i, int j) {
        String temp = this.names[i];
        this.names[i] = this.names[j];
        this.names[j] = temp;
        
    }
    
    static int partition(int array[], int low, int high) {
    
    // choose the rightmost element as pivot
    int pivot = array[high];
    
    // pointer for greater element
    int i = (low - 1);

    // traverse through all elements
    // compare each element with pivot
    for (int j = low; j < high; j++) {
      if (array[j] <= pivot) {

        // if element smaller than pivot is found
        // swap it with the greater element pointed by i
        i++;

        // swapping element at i with element at j
        int temp = array[i];
        array[i] = array[j];
        array[j] = temp;
      }

    }

    // swapt the pivot element with the greater element specified by i
    int temp = array[i + 1];
    array[i + 1] = array[high];
    array[high] = temp;

    // return the position from where partition is done
    return (i + 1);
    }
    
    static void quickSort(int array[], int low, int high) {
    if (low < high) {

      // find pivot element such that
      // elements smaller than pivot are on the left
      // elements greater than pivot are on the right
      int pi = partition(array, low, high);
      
      // recursive call on the left of pivot
      quickSort(array, low, pi - 1);

      // recursive call on the right of pivot
      quickSort(array, pi + 1, high);
    }
  }
}

